# SPDX-License-Identifier: GPL-2.0+

obj-y += ubus/
obj-y += ubfi/
obj-$(CONFIG_UB_URMA) += urma/
obj-$(CONFIG_UB_UBASE) += ubase/
obj-$(CONFIG_UB_CDMA) += cdma/
obj-y += obmm/
obj-$(CONFIG_UB_SENTRY) += sentry/
