
# SPDX-License-Identifier: GPL-2.0+

obmm-y := obmm_core.o \
	obmm_cache.o \
	obmm_export_from_user.o conti_mem_allocator.o \
	obmm_export.o obmm_export_from_pool.o \
	ubmempool_allocator.o obmm_export_region_ops.o \
	obmm_addr_check.o

obj-$(CONFIG_OBMM) += obmm.o
