# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015 - 2022 Beijing WangXun Technology Co., Ltd.
#
# Makefile for the Wangxun(R) 10GbE PCI Express ethernet driver
#

obj-$(CONFIG_TXGBE) += txgbe.o

txgbe-objs := txgbe_main.o \
              txgbe_hw.o \
              txgbe_phy.o \
              txgbe_ethtool.o \
			  txgbe_bp.o \
			  txgbe_dcb_nl.o \
			  txgbe_dcb.o \
			  txgbe_debugfs.o \
			  txgbe_fcoe.o \
			  txgbe_mbx.o \
			  txgbe_mtd.o \
			  txgbe_param.o \
			  txgbe_ptp.o \
			  txgbe_procfs.o \
			  txgbe_sriov.o \
			  txgbe_sysfs.o \
			  txgbe_xsk.o \
			  txgbe_lib.o \
			  txgbe_pcierr.o \
			  txgbe_kcompat.o