/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _YK3_LAN_REGS_H
#define _YK3_LAN_REGS_H

#include "yk3.h"

#define YK3_LAN_BASE	0xc00000
/* yk3 lan tx regs */
/* yk3 lan tx global regs start */
#define YK3_LAN_TX_GLOBAL_BASE (YK3_LAN_BASE + 0x20000)
#define YK3_LAN_TX_GLOBAL_SUBSYSTEM_EN \
	(YK3_LAN_TX_GLOBAL_BASE + 0x0)
#define YK3_LAN_TX_GLOBAL_GLOBAL_MODE \
	(YK3_LAN_TX_GLOBAL_BASE + 0x4)
#define YK3_LAN_TX_GLOBAL_OFFLOAD_MODE \
	(YK3_LAN_TX_GLOBAL_BASE + 0x8)
#define YK3_LAN_TX_GLOBAL_BOTTOM (YK3_LAN_BASE + 0x84)

struct yk3_lan_tx_global_subsystem_en {
	u32 yk3_lan_switch_subsystem_en : 1;
	u32 yk3_lan_offload_subsystem_en : 1;
	u32 yk3_lan_vlantag_subsystem_en : 1;
	u32 yk3_lan_lan_pre_en : 1;
	u32 yk3_lan_lan_parser_en : 1;
	u32 rsvd : 27;
};

#define YK3_LAN_TX_GLOBAL_SWITCH_SUB_EN			GENMASK(0, 0)
#define YK3_LAN_TX_GLOBAL_OFFLOAD_SUB_EN		GENMASK(1, 1)
#define YK3_LAN_TX_GLOBAL_VLANTAG_OFFLOAD_SUB_EN	GENMASK(2, 2)
#define YK3_LAN_TX_GLOBAL_LAN_PRE_SUB_EN		GENMASK(3, 3)
#define YK3_LAN_TX_GLOBAL_LAN_PARSER_EN			GENMASK(4, 4)
#define YK3_LAN_TX_GLOBAL_SUBSYSTEM_RSVD		GENMASK(31, 5)

struct yk3_lan_tx_global_mode {
	u32 yk3_lan_loop_enable : 1;
	u32 yk3_lan_vlan_bitflag_en : 1;
	u32 rsvd : 30;
};

#define YK3_LAN_TX_GLOBAL_LOOP_ENABLE		GENMASK(0, 0)
#define YK3_LAN_TX_GLOBAL_VLAN_BITFLAG_EN	GENMASK(1, 1)
#define YK3_LAN_TX_GLOBAL_MODE_RSVD		GENMASK(31, 2)
/* yk3 lan tx global regs end */

/* yk3 lan tx qset regs start */
#define YK3_LAN_TX_DST_QSET_BASE (YK3_LAN_BASE + 0x0)
#define YK3_LAN_TX_DST_QSET_BUTTOM (YK3_LAN_BASE + 0x1FFF)
#define YK3_LAN_TX_DST_QSET_ENTRY_NUMB (0x800)
#define YK3_LAN_TX_DST_QSET_ENTRY_LEN (0x4)

#define YK3_LAN_TX_DST_QSET_TOTAL_LEN \
	(YK3_LAN_TX_DST_QSET_BUTTOM - \
	 YK3_LAN_TX_DST_QSET_BASE)

#define YK3_LAN_TX_DST_QSET(n) \
	(YK3_LAN_TX_DST_QSET_BASE + (n) * 0x4)

#define YK3_LAN_TX_QSET_NUM (0x200)
#define YK3_LAN_TX_REP_QSET_NUM (0x200)

struct yk3_lan_tx_dst_qset {
	u32 yk3_lan_tx_dst_qset_value : 16;
	u32 yk3_lan_tx_dst_qset_trust : 1;
	u32 yk3_lan_tx_dst_qset_pass_through : 1;
	u32 yk3_lan_tx_dst_qset_rsvd : 14;
};

#define YK3_LAN_TX_DST_QSET_VALUE                   GENMASK(15, 0)
#define YK3_LAN_TX_DST_QSET_TRUST                   GENMASK(16, 16)
#define YK3_LAN_TX_DST_QSET_PASSTHROUGH             GENMASK(17, 17)
#define YK3_LAN_TX_DST_QSET_PASSTHROUGH_VALID       GENMASK(18, 18)
#define YK3_LAN_TX_DST_QSET_RSVD                    GENMASK(31, 19)

#define YK3_LAN_TX_QSET_QINQ_CFG_BASE (YK3_LAN_BASE + 0x2000)
#define YK3_LAN_TX_QSET_QINQ_CFG_BOTTOM (YK3_LAN_BASE + 0x3FFF)
#define YK3_LAN_TX_QSET_QINQ_CFG_TOTAL_LEN \
	(YK3_LAN_TX_QSET_QINQ_CFG_BOTTOM - \
	 YK3_LAN_TX_QSET_QINQ_CFG_BASE)

#define YK3_LAN_TX_QSET_QINQ_CFG(qset)	\
	(YK3_LAN_TX_QSET_QINQ_CFG_BASE + ((qset) * (0x4)))

struct yk3_lan_tx_qset_qinq_cfg {
	u32 qinq_pvid : 12;
	u32 qinq_cfi : 1;
	u32 qinq_pri : 3;
	u32 qinq_type : 16;
};

#define YK3_LAN_TX_QSET_QINQ_CFG_PVID		GENMASK(11, 0)
#define YK3_LAN_TX_QSET_QINQ_CFG_CFI		GENMASK(12, 12)
#define YK3_LAN_TX_QSET_QINQ_CFG_PRI		GENMASK(15, 13)
#define YK3_LAN_TX_QSET_QINQ_CFG_QINQ_TYPE	GENMASK(31, 16)

#define YK3_LAN_TX_QSET_OFFLOAD_VEB_BASE (YK3_LAN_BASE + 0x4000)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_BOTTOM (YK3_LAN_BASE + 0x5FFF)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_TOTAL_LEN \
	(YK3_LAN_TX_QSET_OFFLOAD_VEB_BOTTOM - \
	 YK3_LAN_TX_QSET_OFFLOAD_VEB_BASE)

#define YK3_LAN_TX_QSET_OFFLOAD_VEB(qset)	\
	(YK3_LAN_TX_QSET_OFFLOAD_VEB_BASE + ((qset) * (0x4)))

struct yk3_lan_offload_veb {
	u32 vlan_type : 16;
	u32 veb_enable : 1;
	u32 qinq_vlan_mode : 1;
	u32 inner_vlan_trust : 1;
	u32 src_mac_filter_enable : 1;
	u32 rsvd : 12;
};

#define YK3_LAN_TX_QSET_OFFLOAD_VEB_VLAN_TYPE		GENMASK(15, 0)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_VEB_EN		GENMASK(16, 16)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_QINQ_VLAN_MODE	GENMASK(17, 17)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_INNER_VLAN_TRUST	GENMASK(18, 18)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_SRC_MAC_FILTER_EN	GENMASK(19, 19)
#define YK3_LAN_TX_QSET_OFFLOAD_VEB_RSVD		GENMASK(31, 20)

#define YK3_LAN_TX_VPORT_BASE (YK3_LAN_BASE + 0x6000)
#define YK3_LAN_TX_VPORT_BOTTOM (YK3_LAN_BASE + 0x7FFF)
#define YK3_LAN_TX_VPORT_TOTAL_LEN \
	(YK3_LAN_TX_VPORT_BOTTOM - \
	 YK3_LAN_TX_VPORT_BASE)
/* yk3 lan tx qset regs end */
#define YK3_LAN_TX_SRC_MAC_FILTER_DROP_BASE (YK3_LAN_BASE + 0x30000)
#define YK3_LAN_TX_SRC_MAC_FILTER_DROP_BOTTOM (YK3_LAN_BASE + 0x31FFF)
#define YK3_LAN_TX_SRC_MAC_FILTER_DROP_CNT(qset)	\
	(YK3_LAN_TX_SRC_MAC_FILTER_DROP_BASE + ((qset) * (0x8)))
/* yk3 lan tx regs */

/* yk3 lan rx regs */
/* yk3 lan rx global regs start */
#define YK3_LAN_RX_GLOBAL_BASE (YK3_LAN_BASE + 0x100000)
#define YK3_LAN_RX_GLOBAL_BOTTOM (YK3_LAN_BASE + 0x10FFFF)

#define YK3_LAN_RX_PARSER_EN \
	(YK3_LAN_RX_GLOBAL_BASE + 0x34)

struct yk3_lan_rx_parser_enable {
	u32 parser_enable : 1;
	u32 rsvd : 31;
};

#define YK3_LAN_RX_PARSER_ENABLE		GENMASK(0, 0)
#define YK3_LAN_RX_PARSER_RSVD			GENMASK(31, 1)

#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY0 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x168)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY1 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x170)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY2 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x178)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY3 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x180)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY4 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x188)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY5 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x190)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY6 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x198)
#define YK3_LAN_RX_ESW_RSVD_MC_MATCH_KEY7 \
	(YK3_LAN_RX_ESW_GLOBAL_BASE + 0x1a0)

struct yk3_lan_rx_rsvd_mc_key {
	u32 mc_key_lo32bits;
	u32 mc_key_hi16bits : 16;
	u32 mc_key_mask_len : 6;
	u32 valid : 1;
	u32 rsvd : 9;
};

#define YK3_LAN_RX_ESW_RSVD_MC_MAC_LO32BITS	GENMASK(31, 0)
#define YK3_LAN_RX_ESW_RSVD_MC_MAC_HI16BITS	GENMASK(15, 0)
#define YK3_LAN_RX_ESW_RSVD_MC_KEY_MASK_LEN	GENMASK(21, 16)
#define YK3_LAN_RX_ESW_RSVD_MC_MAC_VALID	GENMASK(22, 22)
#define YK3_LAN_RX_ESW_RSVD_MC_RSVD		GENMASK(31, 23)
/* yk3 lan rx global regs end */

/* yk3 lan rx qset regs start */
#define YK3_LAN_RX_QSET_BASE (YK3_LAN_BASE + 0x110000)
#define YK3_LAN_RX_QSET_BOTTOM (YK3_LAN_BASE + 0x11FFFF)

#define YK3_LAN_RX_QSET_TOTAL_LEN \
	(YK3_LAN_RX_QSET_BOTTOM - YK3_LAN_RX_QSET_BASE)

#define YK3_LAN_RX_QSET_ENTRY_LEN (0x10)

#define YK3_LAN_RX_QSET_NUM (0x200)
#define YK3_LAN_RX_REP_QSET_NUM (0x200)

#define YK3_LAN_RX_REP_QSET_BASE \
	(YK3_LAN_RX_QSET_BASE + (YK3_LAN_RX_QSET_NUM * 2 * YK3_LAN_RX_QSET_ENTRY_LEN))

#define YK3_LAN_RX_QSET(n) \
	(YK3_LAN_RX_QSET_BASE + ((n) * YK3_LAN_RX_QSET_ENTRY_LEN))

#define YK3_LAN_RX_REP_QSET(n) \
	(YK3_LAN_RX_REP_QSET_BASE + ((n) * YK3_LAN_RX_QSET_ENTRY_LEN))

#define YK3_LAN_RX_QSET_HASH(n) (YK3_LAN_RX_QSET(n))
#define YK3_LAN_RX_REP_QSET_HASH(n) (YK3_LAN_RX_REP_QSET(n))
#define YK3_LAN_RX_HASH_TUNNEL_PKT_SEL_OUTER	1
#define YK3_LAN_RX_HASH_TUNNEL_PKT_SEL_INNER	0

struct yk3_lan_rx_qset_hash {
	u32 q_ipv6_tcp_hash_mode : 5;
	u32 q_ipv6_udp_hash_mode : 5;
	u32 q_ipv4_tcp_hash_mode : 5;
	u32 q_ipv4_udp_hash_mode : 5;
	u32 q_tunnel_pkt_hash_sel : 1;	// 1 use udp tunnel head info, 0 use tunnel payload info
	u32 rsvd : 11;
};

#define YK3_LAN_RX_QSET_HASH_MODE_IPV6_TCP	GENMASK(4, 0)
#define YK3_LAN_RX_QSET_HASH_MODE_IPV6_UDP	GENMASK(9, 5)
#define YK3_LAN_RX_QSET_HASH_MODE_IPV4_TCP	GENMASK(14, 10)
#define YK3_LAN_RX_QSET_HASH_MODE_IPV4_UDP	GENMASK(19, 15)
#define YK3_LAN_RX_QSET_TUNNEL_PKT_HASH_SEL	GENMASK(20, 20)
#define YK3_LAN_RX_QSET_HASH_MODE_RSVD		GENMASK(31, 21)

#define YK3_LAN_RX_QSET_MTU(n) (YK3_LAN_RX_QSET(n) + 0x4)
#define YK3_LAN_RX_REP_QSET_MTU(n) (YK3_LAN_RX_REP_QSET(n) + 0x4)

struct yk3_lan_rx_qset_mtu_misc {
	u32 q_mtu : 14;
	u32 q_vlan_offload_mode : 2;
	u32 rsvd : 1;
	u32 q_over_mtu_drop : 1;
	u32 q_fcs_err_drop : 1;
	u32 q_check_err_drop : 1;
	u32 rsvd_1 : 1;
	u32 vport : 4;
	u32 rsvd_2 : 7;
};

enum {
	YK3_LAN_RX_VLAN_STRIP_BYPASS = 0x0,
	YK3_LAN_RX_VLAN_STRIP_CTAG   = 0x1,
	YK3_LAN_RX_VLAN_STRIP_STAG   = 0x2,
	YK3_LAN_RX_VLAN_STRIP_ALL    = 0x3,
};

#define YK3_LAN_RX_QSET_MTU_MISC_MTU			GENMASK(13, 0)
#define YK3_LAN_RX_QSET_MTU_MISC_VLAN_STRIP_MODE	GENMASK(15, 14)
#define YK3_LAN_RX_QSET_MTU_MISC_RSVD			GENMASK(16, 16)
#define YK3_LAN_RX_QSET_MTU_MISC_OVER_MTU_DROP		GENMASK(17, 17)
#define YK3_LAN_RX_QSET_MTU_MISC_FCS_ERR_DROP		GENMASK(18, 18)
#define YK3_LAN_RX_QSET_MTU_MISC_CHKSUM_ERR_DROP	GENMASK(19, 19)
#define YK3_LAN_RX_QSET_MTU_MISC_RSVD_1			GENMASK(20, 20)
#define YK3_LAN_RX_QSET_MTU_MISC_VPORT			GENMASK(24, 21)
#define YK3_LAN_RX_QSET_MTU_MISC_RSVD_2			GENMASK(31, 25)

#define YK3_LAN_RX_QSET_VLAN_MISC(n) (YK3_LAN_RX_QSET(n) + 0x8)
#define YK3_LAN_RX_REP_QSET_VLAN_MISC(n) (YK3_LAN_RX_REP_QSET(n) + 0x8)

struct yk3_lan_rx_qset_vlan_misc {
	u32 pvid : 12;
	u32 pvid_type : 1;
	u32 pvid_valid : 1;
	u32 pvid_bypass : 1;
	u32 stag_vlan_valid : 1;
	u32 ctag_vlan_valid : 1;
	u32 bc_disable : 1;
	u32 smartnic_promiscuous : 1;
	u32 umc_flood_enable : 1;
	u32 promiscuous_enable : 1;
	u32 src_dst_qset_filter : 1;
	u32 q_port0_en : 1;
	u32 q_port1_en : 1;
	u32 q_port2_en : 1;
	u32 q_port3_en : 1;
	u32 q_port4_en : 1;
	u32 q_port5_en : 1;
	u32 q_port6_en : 1;
	u32 q_port7_en : 1;
	u32 pvid_tpid_type : 2;
};

#define YK3_LAN_RX_QSET_VLAN_MISC_PVID			GENMASK(11, 0)
#define YK3_LAN_RX_QSET_VLAN_MISC_RSVD			GENMASK(12, 12)
#define YK3_LAN_RX_QSET_VLAN_MISC_PVID_VALID		GENMASK(13, 13)
#define YK3_LAN_RX_QSET_VLAN_MISC_PVID_BYPASS		GENMASK(14, 14)
#define YK3_LAN_RX_QSET_VLAN_MISC_STAG_VLAN_VALID	GENMASK(15, 15)
#define YK3_LAN_RX_QSET_VLAN_MISC_CTAG_VLAN_VALID	GENMASK(16, 16)
#define YK3_LAN_RX_QSET_VLAN_MISC_BC_DISABLE		GENMASK(17, 17)
#define YK3_LAN_RX_QSET_VLAN_MISC_SMARTNIC_PROMISCUOUS	GENMASK(18, 18)
#define YK3_LAN_RX_QSET_VLAN_MISC_RECV_UMC		GENMASK(19, 19)
#define YK3_LAN_RX_QSET_VLAN_MISC_PROMISCUOUS_ENABLE	GENMASK(20, 20)
#define YK3_LAN_RX_QSET_VLAN_MISC_SRC_EQ_DST_DROP	GENMASK(21, 21)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_0_ENABLE		GENMASK(22, 22)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_1_ENABLE		GENMASK(23, 23)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_2_ENABLE		GENMASK(24, 24)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_3_ENABLE		GENMASK(25, 25)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_4_ENABLE		GENMASK(26, 26)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_5_ENABLE		GENMASK(27, 27)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_6_ENABLE		GENMASK(28, 28)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_7_ENABLE		GENMASK(29, 29)
#define YK3_LAN_RX_QSET_VLAN_MISC_PORT_ENABLE		GENMASK(29, 22)
#define YK3_LAN_RX_QSET_VLAN_MISC_PVID_TYPE		GENMASK(31, 30)
/* yk3 lan rx qset regs end */

/* yk3 lan rx esw regs start */
#define YK3_LAN_ESW_MAC_FILTER_BASE (YK3_LAN_BASE + 0x120000)
#define YK3_LAN_ESW_MAC_FILTER_ENTRY_SIZE (0x8)
#define YK3_LAN_ESW_MAC_FILTER_BUCKET_NUMB (0x3)
#define YK3_LAN_ESW_MAC_FILTER_BUCKET_SIZE (0x8000)
#define YK3_LAN_ESW_MAC_FILTER_BOTTOM (YK3_LAN_BASE + 0x13FFFF)
#define YK3_LAN_ESW_MAC_FILTER_TOTAL_LEN \
	(YK3_LAN_ESW_MAC_FILTER_BOTTOM - YK3_LAN_ESW_MAC_FILTER_BASE)

#define YK3_LAN_ESW_MAC_QSET_BMP_BASE (YK3_LAN_BASE + 0x140000)
#define YK3_LAN_ESW_MAC_QSET_BMP_BOTTOM (YK3_LAN_BASE + 0x17FFFF)
#define YK3_LAN_ESW_MAC_QSET_ENTRY_LEN (0x80)
#define YK3_LAN_ESW_MAC_QSET_BMP_NUMB (0x800)
#define YK3_LAN_ESW_UC_MAC_QSET_BMP_NUMB (0x400)
#define YK3_LAN_ESW_MC_MAC_QSET_BMP_NUMB (0x400)
#define YK3_LAN_ESW_MAC_QSET_BMP_TOTAL_LEN \
	(YK3_LAN_ESW_MAC_QSET_BMP_BOTTOM - YK3_LAN_ESW_MAC_QSET_BMP_BASE)

#define YK3_LAN_ESW_MAC_QSET_BMP_ENTRY_ADDR(n) \
	(YK3_LAN_ESW_MAC_QSET_BMP_BASE + \
	 ((n) * (YK3_LAN_ESW_MAC_QSET_ENTRY_LEN)))

#define YK3_LAN_ESW_VLAN_FILTER_BASE (YK3_LAN_BASE + 0x270000)
#define YK3_LAN_ESW_VLAN_FILTER_TYPE0_BASE (YK3_LAN_BASE + 0x270000)
#define YK3_LAN_ESW_VLAN_FILTER_TYPE1_BASE (YK3_LAN_BASE + 0x274000)
#define YK3_LAN_ESW_VLAN_FILTER_BOTTOM (YK3_LAN_BASE + 0x27FFFF)

#define YK3_LAN_ESW_VLAN_FILTER_ENTRY_NUMB (0x1000)
#define YK3_LAN_ESW_VLAN_FILTER_ENTRY_LEN (0x4)

#define YK3_LAN_ESW_VLAN_FILTER_TOTAL_LEN \
	(YK3_LAN_ESW_VLAN_FILTER_ENTRY_NUMB * YK3_LAN_ESW_VLAN_FILTER_ENTRY_LEN)

#define YK3_LAN_ESW_VLAN_FILTER_VLAN_ENTRY_OFFSET(vid) \
	((vid) * YK3_LAN_ESW_VLAN_FILTER_ENTRY_LEN)

struct yk3_lan_esw_vlan_filter {
	u32 vlan_qset_bmp_index : 12;
	u32 vlan_enable : 1;
	u32 rsvd : 19;
};

#define YK3_LAN_ESW_VLAN_FILTER_QSET_BMP_INDEX	GENMASK(11, 0)
#define YK3_LAN_ESW_VLAN_FILTER_ENABLE		GENMASK(12, 12)
#define YK3_LAN_ESW_VLAN_FILTER_RSVD		GENMASK(31, 13)

#define YK3_LAN_ESW_VLAN_QSET_BMP_BASE (YK3_LAN_BASE + 0x280000)
#define YK3_LAN_ESW_VLAN_QSET_BMP_BOTTOM (YK3_LAN_BASE + 0x2FFFFF)
#define YK3_LAN_ESW_VLAN_QSET_BMP_NUMS (0x1000)
#define YK3_LAN_ESW_VLAN_QSET_BMP_TOTAL_LEN \
	(YK3_LAN_ESW_VLAN_QSET_BMP_BOTTOM - \
	 YK3_LAN_ESW_VLAN_QSET_BMP_BASE)

#define YK3_LAN_ESW_VLAN_QSET_BMP_ENTRY_LEN (0x80)

#define YK3_LAN_ESW_VLAN_QSET_BMP_ENTRY_ADDR(n) \
	(YK3_LAN_ESW_VLAN_QSET_BMP_BASE + \
	 ((n) * YK3_LAN_ESW_VLAN_QSET_BMP_ENTRY_LEN))
/* yk3 lan rx esw regs start */
/* yk3 lan rx regs */

/* lan statistics regiters */
#define YK3_LAN_RX_DEBUG_STATS_BASE			(YK3_LAN_BASE + 0x3E0000)
#define YK3_LAN_RX_DEBUG_STATS_SW_DROP_CNT_CH0		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10C0)
#define YK3_LAN_RX_DEBUG_STATS_SW_HIT_CNT_CH0		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10C8)
#define YK3_LAN_RX_DEBUG_STATS_SW_DROP_CNT_CH1		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10D0)
#define YK3_LAN_RX_DEBUG_STATS_SW_HIT_CNT_CH1		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10D8)
#define YK3_LAN_RX_DEBUG_STATS_SW_DROP_CNT_CH2		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10E0)
#define YK3_LAN_RX_DEBUG_STATS_SW_HIT_CNT_CH2		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10E8)
#define YK3_LAN_RX_DEBUG_STATS_SW_DROP_CNT_CH3		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10F0)
#define YK3_LAN_RX_DEBUG_STATS_SW_HIT_CNT_CH3		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x10F8)

#define YK3_LAN_RX_DEBUG_STATS_MAC_MISS_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1108)
#define YK3_LAN_RX_DEBUG_STATS_FIRST_VLAN_MISS_CNT	(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1118)
#define YK3_LAN_RX_DEBUG_STATS_SECOND_VLAN_MISS_CNT	(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1120)
#define YK3_LAN_RX_DEBUG_STATS_PVID_MISS_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1128)
#define YK3_LAN_RX_DEBUG_STATS_VEB_DROP_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1130)
#define YK3_LAN_RX_DEBUG_STATS_FCS_DROP_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1138)
#define YK3_LAN_RX_DEBUG_STATS_CHKSUM_DROP_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1140)
#define YK3_LAN_RX_DEBUG_STATS_MTU_DROP_CNT		(YK3_LAN_RX_DEBUG_STATS_BASE + 0x1148)
/* yk3 lan rx regs */

#endif /* _YK3_LAN_REGS_H */
