// SPDX-License-Identifier: GPL-2.0

#include "yk3_chip.h"
#include "yk3_doe_hw.h"
/******************************************************************************/
#define YK3_CHIP_DOE_CACHE_ENTRY_COUNT_K3 { \
	[YK3_DOE_AIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_AIE_CACHE_128B_COUNT_K3, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_AIE_CACHE_64B_COUNT_K3, \
	}, \
	[YK3_DOE_CIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_CIE_CACHE_16B_COUNT_K3, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_CIE_CACHE_16B_COUNT_K3, \
	}, \
	[YK3_DOE_MIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_MIE_CACHE_32B_COUNT_K3, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_MIE_CACHE_32B_COUNT_K3, \
	}, \
	[YK3_DOE_HIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_HIE_CACHE_128B_COUNT_K3, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_HIE_CACHE_64B_COUNT_K3, \
	}, \
}

#define YK3_CHIP_DOE_CACHE_ENTRY_COUNT_K3MAX { \
	[YK3_DOE_AIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_AIE_CACHE_128B_COUNT_K3MAX, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_AIE_CACHE_64B_COUNT_K3MAX, \
	}, \
	[YK3_DOE_CIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_CIE_CACHE_16B_COUNT_K3MAX, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_CIE_CACHE_16B_COUNT_K3MAX, \
	}, \
	[YK3_DOE_MIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_MIE_CACHE_32B_COUNT_K3MAX, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_MIE_CACHE_32B_COUNT_K3MAX, \
	}, \
	[YK3_DOE_HIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_HIE_CACHE_128B_COUNT_K3MAX, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_HIE_CACHE_64B_COUNT_K3MAX, \
	}, \
	[YK3_DOE_LHIE] = { \
		[YK3_DOE_CACHE_MODE_LONG]  = YK3_DOE_LHIE_CACHE_16B_COUNT_K3MAX, \
		[YK3_DOE_CACHE_MODE_SHORT] = YK3_DOE_LHIE_CACHE_16B_COUNT_K3MAX, \
	}, \
}

const struct yk3_chip_spec yk3_chip_specs[YK3_CHIP_END] = {
	[YK3_K3] = {
		.doe = {
			.version = YK3_DOE_VERSION_K3,
			.protect_ack = YK3_DOE_PROTECT_ACK_K3,
			.hash_table_limit = YK3_DOE_HASH_TABLE_LIMIT_K3,
			.index_sram_size = YK3_DOE_INDEX_SRAM_SIZE_K3,
			.ddr_channel = YK3_DOE_CHANNEL_DDR0,
			.cache_entry_count = YK3_CHIP_DOE_CACHE_ENTRY_COUNT_K3,
		},
	},

	[YK3_K3MAX] = {
		.doe = {
			.version = YK3_DOE_VERSION_K3MAX,
			.protect_ack = YK3_DOE_PROTECT_ACK_K3MAX,
			.hash_table_limit = YK3_DOE_HASH_TABLE_LIMIT_K3MAX,
			.index_sram_size = YK3_DOE_INDEX_SRAM_SIZE_K3MAX,
			.ddr_channel = YK3_DOE_CHANNEL_DDR1,
			.cache_entry_count = YK3_CHIP_DOE_CACHE_ENTRY_COUNT_K3MAX,
		},
	},
};
