# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
# Create      : 2025-04-18
# Description : cis Makefile

obj-$(CONFIG_UDFI_CIS) += cis.o

cis-objs := cis_info_process.o uvb_info_process.o cis_core.o io_param.o

ccflags-y += -I$(srctree)/$(src)/../include
