# SPDX-License-Identifier: GPL-2.0

TEST_GEN_FILES := netbind_test shield_mounts_test signal_test
TEST_PROGS := netbind.sh killprotect.sh killblock.sh irqlatency.sh \
	memcg_async.sh shield_mounts.sh cgroupfs.sh
TEST_FILES := tkernel.sh

include ../lib.mk
