# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the sentry drivers.

obj-$(CONFIG_UB_SENTRY) += sentry_msg_helper.o
obj-$(CONFIG_UB_SENTRY) += sentry_reporter.o

sentry_msg_helper-y := smh_core.o smh_message.o
