obj-$(CONFIG_NGBE) += ngbe.o

ngbe-objs := ngbe_main.o \
			 ngbe_hw.o \
			 ngbe_phy.o \
			 ngbe_ethtool.o \
			 ngbe_lib.o \
			 ngbe_mbx.o \
			 ngbe_sriov.o \
			 ngbe_pcierr.o \
			 ngbe_param.o \
			 ngbe_procfs.o \
			 ngbe_ptp.o \
			 ngbe_sysfs.o \
			 ngbe_debugfs.o \
			 ngbe_kcompat.o