# SPDX-License-Identifier: GPL-2.0-or-later

# Copyright (c) 2024, DapuStor Corporation.

obj-m := dn200.o
dn200-objs :=   \
              dn200_main.o dn200_ethtool.o dn200_mdio.o ring_mode.o	\
              mmc_core.o dn200_hwtstamp.o dn200_ptp.o \
              hwif.o \
              dwxgmac2_core.o dwxgmac2_dma.o dwxgmac2_descs.o \
              dn200_selftests.o dn200_pci.o\
              dn200_sriov.o dn200_ctrl.o \
              dn200_phy_impl.o dn200_spec_acc.o \
              dn200_dcb.o dn200_eprom.o dn200_iatu.o dn200_pool.o dn200_reg.o \
              extern_phy.o
